name: Warm VS Code Cache

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  warm-cache:
    uses: ./.github/workflows/build-vscode.yaml
    with:
      upload-artifact: false
    secrets: inherit
